### ISSUE TITLE
Downloading does not work

### ISSUE THREAD

**Issue by BullyWiiPlaza** [dojafoja/FunKii-UI#15]
I've configured my output path to be the same as the `FunKii-UI` root directory after leaving it empty but either one does not work. The games are listed but when I start downloading, nothing happens:

![image](https://user-images.githubusercontent.com/7620135/50384306-579ff180-06c3-11e9-8e5d-c0b1d16aa36f.png)

![image](https://user-images.githubusercontent.com/7620135/50384310-638bb380-06c3-11e9-9492-cdd3fb063867.png)

![image](https://user-images.githubusercontent.com/7620135/50384324-96ce4280-06c3-11e9-9141-345ae688841e.png)

There isn't even an `install` folder and the process cannot finish in like 1 second when it needs to download like `6GB`. What is going wrong here? Is `FunKii-UI` disfunct?

I'm running the latest commit build: https://github.com/dojafoja/FunKii-UI/commit/bf825ee3442c7c4ffb4bfbacb3ceda1f7f32e247

**Comment by dojafoja** [comment]
I don't know how but you have selected Simulation mode in the options settings. Just switch to the options tab and turn off Simulation mode. It's a stupid feature that was included in FunkiiU that I included in the GUI as well. It's stupid and im going to remove the option I the next release. I may have accidentally left it as the default option in the master branch, since I'm not quite finished with what I'm doing there.

**Comment by dojafoja** [comment]
Well I wouldn't say it's a completely useless feature, I actually use it a lot while developing new features that's probably how I accidentally left it on in the first place. I use it so I can still click download and verify that any new changes didn't crash between point A and point B(the point of download).

**Comment by dojafoja** [comment]
Yes it works just fine! When I push my next round of files, I will fix the issue.  Thanks for pointing that out. Luckily, most people only download published releases so hopefully there isn't too many people downloading from the master branch and having this issue.

**Comment by dojafoja** [comment]
BTW, I'm a fan of your work. Thanks for everything you've done and contributed to the WiiU scene!

**Comment by BullyWiiPlaza** [comment]
Yep, release v2.1.8 works fine
