### ISSUE TITLE
File Size Database Mismatching

### ISSUE THREAD

**Issue by ShakesU** [dojafoja/FunKii-UI#4]
For example: 0005000e1010f800 and 0005000e10111d00 and 0005000e1010fc00 ... fail with incorrect file size, unable to d/l. Appears not isolated to a few.

Need to remove 0005000010110800 and 0005000e10110800 entirely from database as is known has corrupt update/patch on server, and does not work correctly on Wii U. Ubi-S would not fix a long time ago. It does work however on original platform it was released on. Unsure if this issue is region specific. Such a shame though.

Thank-you.

**Comment by dojafoja** [comment]
My file size database is used for reference only. Its only purpose is to show the user the total size prior to downloading. Its how I calculate total download sizes in the GUI. The expected file sizes are actually parsed straight from the TMD at the point of download by FunKiiU. If its mismatching then the downloaded size doesn't match the expected size that was parsed from the TMD. I'm not sure why this is happening tbh unless they have not updated TMD information, the files on their servers are corrupt OR FunKiiU isn't handling special case scenarios properly while parsing that info. Is there some kind of known 'blacklist' of titles that fail to download correctly that I can use to filter my selection menu? I will implement my own txt file blacklist that my GUI will use to not display any title contained within it. Then I can just easily add problematic titles to it and it will automatically be filtered out. Thanks for raising this issue.

**Comment by ShakesU** [comment]
Then it appears a 'blacklist' would be in order. I had tried multiple passes of the same rules to no avail. Is there a way to of circumventing TMD in blacklisted files? Just a thought, otherwise some title updates will remain broken with user warning I guess is all is left to do.

Ticket is closed anyway. Appeciate your efforts and response. At least you're aware.

**Comment by dojafoja** [comment]
I've got a blacklist feature that works now with a blacklist.txt file containing bad title id's. The other thing in think is maybe a corrected-size.txt file that would contain a title id and a corrected size, in bytes. It would be really easy to cross reference this list of corrected sizes at the point of size verification. Idk, none of them really seem like a clean solution but I think the only way to 'fix' it is to decrypt the content and verify the size and hash that way. Problem is I don't think python comes with a crypto library and would require more dependencies on the end user. Plus if I remember, decryption is rather slow on python.

**Comment by dojafoja** [comment]
I keep accidentally closing this issue lol.

**Comment by ShakesU** [comment]
Yeah, too much messing around when it's all not a huge issue, just ones that hundreds will bump into, and makes your UI unique if it can save the pain of fails. Cheers for that! Will have a look soon. After backing everything up, I had done a reinstall, and clean out from the years of cluttered, and fragmented data :-P, so everything was put on hold for a bit. However, me wonders if is is a way users can assist with blacklists, or can you see them alright, and think best to keep user input out of the loop because of fake, or mistaken reporting? I'll see a reply, but won't necessarily acknowledge with a response :-) Don't forget that one Aveng... title that downloads ok, but no good with bad update for use on U console. Better close this again hahaha. Thanks dojafoja. Good work. I find a separate UI way from home brew easier to catalog, and archive data. Have 2TB is on WU, and backup install files... FKU real easy to use now (not being rude with FKU ^_^.) *Puts on the feathered Tricorn again* I have small children that are happy now. Servers appear to be congesting though, thinking this may not last. Better close this a couple more times for good measure hahaha!

**Comment by ShakesU** [comment]
Really Broken Now. Just had the chance to try. As always, file size on host in 'None.' Nothing has changed with that. I see file size on disk, ok, kind of helpful, but not relevant if not using TMD to cross 'hash.' Now I have every file refusing to initiate due to 'None.' Is this the blacklist? If so, it was broken before, and the 'fix,' has now made it not work at all. It was the 'None' that made it uncertain as to if the file was fully successful or not. SmBros.U DLC no go, MK8-DLC no go, B10-O & B10-O2 both broken/no display but green polygon pattern on both. I am unable to re-pass these d/l to confirm any host error, or bad d/l my end due to congestion on district internet crawl, and/or host congestion crawl errors, and because 'none' and TMD don't purposefully match, 'none' has blacklisted everything me thinks. Remember though, it was always 'none' before this.

Update also fails from that site. Appears to be broken association.

Try rolling back to previous FKU version, and FKU it won't initiate at all.

Going to try another UI to see if more fruitful. Thanks for your attempts, hope you get it sorted, because it is my preferred method.

**Comment by dojafoja** [comment]
Sorry, I haven't pushed any of my working files. I am aware that it's completely broken atm but I can never seem to find enough time to finalize anything. I appreciate your insight here and I hope I can get a working version out soon. Tbh, I lost interest in the project for a while but I'm hoping to change that.

**Comment by aphirst** [comment]
In light of the recent discontinuation of Wii U USB Helper, is there any likelihood that this issue could get re-explored?

It seems the upstream developers are aware of the issue too: https://github.com/llakssz/FunKiiU/issues/33

**Comment by dojafoja** [comment]
This issue has been sorted out in versions >= 2.1.8
