### ISSUE TITLE
title key site change, can't update the GUI to make it work

### ISSUE THREAD

**Issue by XtraSmiley** [dojafoja/FunKii-UI#8]
Hey, so the old site for keys, wiiu.title****.com is down, now it's .gq and I tired that but the GUI won't take that or .gq/json either. I tired typing that into the config screen as well and still when the terminal box pops up and says type here it won't take it with or without the http, so I'm not sure how to get this to run. Thanks!

Also, anyway to make the GUI accept whatever you type so in the future changes can be inputted? Right now if it's not EXACTLY the correct site, the GUI screen just won't save it. Thanks guys!

**Comment by dojafoja** [comment]
I plan on fixing the issue to allow any key site really soon. For now I have a hot fix you can use that accepts the site ending in .gq You musty user both of these modified files for it to work. Modified FunKiiU: https://www.mediafire.com/file/27qw0aqurqgm4po/FunKiiU.py AND modified GUI: https://www.mediafire.com/file/qszlphf4plljqx8/gui.py

**Comment by XtraSmiley** [comment]
Awesome, that worked, thank you.
